# Generated by Django 4.1.2 on 2022-10-05 19:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(1)])),
                ('introduction', models.CharField(max_length=2000, validators=[django.core.validators.MinLengthValidator(200)])),
                ('release_date', models.DateField()),
                ('duration', models.PositiveBigIntegerField()),
                ('likes', models.PositiveBigIntegerField()),
            ],
        ),
    ]
