# Generated by Django 4.1.2 on 2022-10-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flix', '0002_alter_movie_likes_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='thumbnail',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
