# Generated by Django 4.1.2 on 2022-10-10 11:35

from django.db import migrations, models
import flix.validators


class Migration(migrations.Migration):

    dependencies = [
        ('flix', '0004_alter_movie_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='thumbnail',
            field=models.ImageField(upload_to='', validators=[flix.validators.validate_file_size]),
        ),
    ]
