# Generated by Django 4.1.2 on 2022-10-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flix', '0005_alter_movie_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='likes',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
    ]
