# Generated by Django 4.1.2 on 2022-10-10 12:42

from django.db import migrations, models
import flix.validators


class Migration(migrations.Migration):

    dependencies = [
        ('flix', '0006_alter_movie_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='thumbnail',
            field=models.ImageField(upload_to='files/thumbnails', validators=[flix.validators.validate_file_size]),
        ),
    ]
