# Generated by Django 4.1.2 on 2022-10-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flix', '0008_alter_movie_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cover',
            field=models.ImageField(default=0, upload_to='files/thumbnails'),
            preserve_default=False,
        ),
    ]
