# Generated by Django 4.1.2 on 2022-10-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flix', '0009_movie_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cover',
            field=models.ImageField(upload_to='files/covers'),
        ),
    ]
